### ISSUE TITLE
Desugaring patterns

### ISSUE THREAD

**Issue by j-hui** [ssm-lang/sslang#31]
At the moment, `LowerAst` just bails out when it finds any pattern that isn't a wildcard or an identifier. So the following two (written in OCaml syntax for brevity and syntax highlighting) are both not possible:

```ocaml
let (p, q) = pqdef in pqscope

let f (x, y) = fdef in fscope
```

These should desugar to, respectively

```ocaml
let __pq = pqdef in match __pq with (p, q) -> pqscope

let f __xy = match __xy with (x, y) -> fdef in fscope
```

Then there's the issue of aliases:

```ocaml
let p@q = pqdef in pqscope

let f x@y = fdef in fscope
```

which should desguar to

```ocaml
let p = pqdef in let q = p in pqscope

let f x = let y = x in fdef in fscope
```

These may get tricky in the presence of mutual recursion/parallel let-bindings of variables, and so should probably come after #30 .

-----

Just as a note: I'm not sure how best to desugar mutually recursive name aliases:

```ocaml
let rec f@f' x = fdef
    and g@g' x = gdef
    and h@h' x = hdef
in
fghscope
```
This seems to lead to a combinatorial explosion:

```ocaml
let rec f' x = let g = g' in let h = h' in fdef
    and g' x = let f = f' in let h = h' in gdef
    and h' x = let f = f' in let g = g' in hdef
in
let f = f' in
let g = g' in
let h = h' in
fghscope
```

But for now, that original example is just not allowed by our syntax (and not representable in our AST either).

**Comment by j-hui** [comment]
@sedwards-lab is this the book you're talking about: https://www.microsoft.com/en-us/research/publication/the-implementation-of-functional-programming-languages/

It looks like chapter 5.2 is talking about desugaring Miranda's nested patterns. The notation they use is a little difficult to read though, and also they sugar down to pattern-matching lambdas (which seem similar to case/match expressions as we know them, except expressed as a parallel list of lambdas with patterns in the arguments). But it should certainly be possible to extract the algorithm from this.

**Comment by sedwards-lab** [comment]
Yes, that was the book I was referring to. This is comparatively early work and much more has been done since then, but it's a good place to start, and the other papers should cite this chapter, or perhaps the things the chapter cites.

**Comment by j-hui** [comment]
@LeoQiao18  seems to hahve cracked this in #97 

We have talked about plans to migrate this phase to after typechecking, but for now I consider this closed!
