### ISSUE TITLE
Ar does not work on macOS

### ISSUE THREAD

**Issue by j-hui** [ssm-lang/sslang#35]
@maxhhelman ran into this issue when we were pair programming. If I remember correctly, `ar` on macOS does not recognize the `-U` flag (and I think Zach ran across this issue before too).

It looks like `-U` is the default behavior anyway: https://www.man7.org/linux/man-pages/man1/ar.1.html

We should adjust the ARFLAGS in the ssm-runtime Makefile, maybe just remove that flag if it's not actually necessary, so that we can support building on macOS.

**Comment by sedwards-lab** [comment]
Where, exactly, is the -U flag being used that it's tripping up MacOS?

**Comment by j-hui** [comment]
It's being used in the `Makefile` for ssm-runtime. I included some information about it in this commit message: https://github.com/ssm-lang/sslang/pull/42/commits/08365a5514fa1a380f91e184826b42c755f740d9

**Comment by sedwards-lab** [comment]
As you point out, the best solution is to just get rid of -U
