### ISSUE TITLE
Don't rely on mangled names for AST equivalence checks

### ISSUE THREAD

**Issue by hmontero1205** [ssm-lang/sslang#61]
>when we compare the two programs, we don't really want to compare the mangled names... it suggests that we should have some kind of more sophisticated IR comparison mechanisms modulo alpha renaming.

this was a comment on the following code in lambda lifting unit tests:
```
        nestedToLifted = lowerAndLift nonLiftedProgram
        liftedToLifted = lowerAndLift liftedProgram
    nestedToLifted `shouldBe` liftedToLifted
```

**Comment by j-hui** [comment]
Closed by #71
