### ISSUE TITLE
Add tuple literal syntax

### ISSUE THREAD

**Issue by j-hui** [ssm-lang/sslang#68]
I encountered this issue while working on #58 . Apparently we just don't have any syntax for tuples yet.

This is a pretty easy fix, and should not be too difficult, but will require touching a few files that may conflict with others. Since we can always fake tuples using ADTs, this is not strictly necessary, so I'm deeming this a lower priority compared to getting ADT up and running.

**Comment by sedwards-lab** [comment]
Tuples are just syntactic sugar for ADTs anyway, right? ADTs are definitely the priority

**Comment by j-hui** [comment]
Yep exactly. We can always recover (ugly) tuples with:

```
type Tup2 a b
  Tup2 a b

type Tup3 a b c
  Tup3 a b c

// etc.
```

**Comment by j-hui** [comment]
Seems to have been completed long ago by #138 and various other PRs
